# netlify.toml  (place at the project root)

[build]
  command = "npm run build"
  publish = "dist"

# Where your serverless functions live
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
